server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # Git\u4ED3\u5E93\u5730\u5740
          uri: https://github.com/juncan/spring-cloud-config-repo.git
          # Git\u4ED3\u5E93\u8D26\u53F7
          username: juncan
          # Git\u4ED3\u5E93\u5BC6\u7801
          password: canfang9754
