server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  # \u8981\u76D1\u63A7\u7684\u5FAE\u670D\u52A1\u5217\u8868\uFF0C\u591A\u4E2A\u7528,\u5206\u9694
  appConfig: microservice-consumer-movie,microservice-provider-user
  clusterNameExpression: "'default'"
