server:
  port: 8010
spring:
  application:
    # \u6307\u5B9A\u6CE8\u518C\u5230eureka server\u4E0A\u7684\u670D\u52A1\u540D\u79F0
    name: microservice-consumer-movie

eureka:
  client:
    service-url:
      # \u6307\u5B9Aeureka server\u901A\u4FE1\u5730\u5740\uFF0C\u6CE8\u610F/eureka/\u5C0F\u5C3E\u5DF4\u4E0D\u80FD\u5C11
      defaultZone: http://localhost:8761/eureka/
  instance:
    # \u662F\u5426\u6CE8\u518CIP\u5230eureka server\uFF0C\u5982\u4E0D\u6307\u5B9A\u6216\u8BBE\u4E3Afalse\uFF0C\u90A3\u5C31\u4F1A\u6CE8\u518C\u4E3B\u673A\u540D\u5230eureka server
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        # \u5F00\u653E\u6240\u6709\u76D1\u63A7\u7AEF\u70B9
        include: '*'
  endpoint:
    health:
      # \u662F\u5426\u5C55\u793A\u5065\u5EB7\u68C0\u67E5\u8BE6\u60C5
      show-details: always

feign:
  client:
    config:
      microservice-provider-user:
        loggerLevel: full
    compression:
      request:
        enabled: true
        mime-type: text/xml,application/xml,application/json
        min-request-size: 2048
      response:
        enabled: true

logging:
  level:
    com.may.cloud.feign.UserFeignClient: debug